#Este COMPOSE es para levantar la segunda prueba en otra maquina
#debes poner la direccion IP de la maquina donde esta la base de datos
#este archivo tiene un nombre distinto, para correr ejecuta
#docker compose -f Docker-soloapp.yml up -d
version: '3.1'
services:
  appversus2:
    image: calderonperaza/dbversusapp:1.0
    container_name: appversus2
    restart: unless-stopped    
    ports:
      - "3000:3000"
    environment:
      - HOST_DB=192.168.0.14
    deploy:
          resources:
            limits:
              cpus: '1'
              memory: 1G
            reservations:
              cpus: '1'
              memory: 1G