version: '3.8'
services:
  scylla:
    image: scylladb/scylla:5.4
    container_name: scylla_container
    restart: unless-stopped
    ports:
      - "9042:9042"
    command: --smp 1 --memory 750M --developer-mode 1
    environment:
      - SCYLLA_DEVELOPER_MODE=1
    volumes:
      - ./init.cql:/init.cql
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES' || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 10

  initdb:
    image: scylladb/scylla:5.4
    depends_on:
      scylla:
        condition: service_healthy
    entrypoint: ["/bin/bash", "-c", "cqlsh scylla 9042 -f /init.cql"]
    volumes:
      - ./init.cql:/init.cql
    environment:
      - CQLSH_HOST=scylla
    restart: "no"